version: "3.3"

services:
  postgres:
    image: postgres:14
    environment:
        - POSTGRES_PASSWORD=srv_links
        - POSTGRES_USER=srv_links
        - POSTGRES_DB=srv_links
    ports:
      - '5438:5432'
    command: -c fsync=off -c full_page_writes=off
    tmpfs: /var/lib/postgresql/data


